# This rule is not used by the project histack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ipam.histack.ir.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: histack
    app.kubernetes.io/managed-by: kustomize
  name: clusterippool-editor-role
rules:
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterippools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterippools/status
  verbs:
  - get
