# This rule is not used by the project histack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ipam.histack.ir.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: histack
    app.kubernetes.io/managed-by: kustomize
  name: clusterip-admin-role
rules:
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterips
  verbs:
  - '*'
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterips/status
  verbs:
  - get
