# This rule is not used by the project histack itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ipam.histack.ir resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: histack
    app.kubernetes.io/managed-by: kustomize
  name: clusterip-viewer-role
rules:
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterips
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterips/status
  verbs:
  - get
