---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterippools
  - clusterips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterippools/finalizers
  - clusterips/finalizers
  verbs:
  - update
- apiGroups:
  - ipam.histack.ir
  resources:
  - clusterippools/status
  - clusterips/status
  verbs:
  - get
  - patch
  - update
