apiVersion: ipam.histack.ir/v1alpha1
kind: ClusterIPPool
metadata:
  labels:
    app.kubernetes.io/name: histack
    app.kubernetes.io/managed-by: kustomize
  name: clusterippool-sample
spec:
  # TODO(user): Add fields here
